### ISSUE TITLE
Not finding 'true' #1 branch

### ISSUE THREAD

**Issue by malleeblue** [ArMoraer/QGISStrahler#3]
I am excited at this plugin and have been using it today on my water and sewer layers.
I have found that it does not allocate a Strahler number to the first leaf nodes. In the case of my Sewer layers, the first leaf nodes represent the sewer junction with the dwelling, and in the water layer, the leaf node represents the line between the main and the meter.

I can't see why it is not doing this. Any ideas? Happy to send a file if you would like.

**Comment by ArMoraer** [comment]
Hi malleechick,
This behavior seems strange indeed.
Please send me your file so I can have a look at it.

**Comment by malleeblue** [comment]
[temp.zip](https://github.com/ArMoraer/QGISStrahler/files/148914/temp.zip)

**Comment by ArMoraer** [comment]
Ok, I think I understand. There are 2 problems in your layer (which is quite complex, by the way; good test!):
1. Some of your lines are actually multipolylines, meaning they have a multipart geometry. This concerns lines #19, 96, 585, 2385, 2704, 9716 and 9717 (I think I've got them all). Using the "Multipart to Singleparts" tool beforehand (in Vector > Geometry Tools) solves this issue. I think I will add a warning message in the next version since it might be a common issue.
2. The other problem is that there are several "T" junctions where a line meets another line somewhere between its endpoints. For now, the plugin only works if every "T" junction is made of 3 segments meeting at a common endpoint. One example is line #11245, which meets line #10293 next to an endpoint but not right on it. Fortunately, there is also a tool to solve this: "Explode lines" (in Processing > Toolbox > QGIS Geoalgorithms > Vector geometry tools). This will create a new layer where lines are divided into smaller segments.

After applying these 2 tools, a bigger part of your network gets Strahler numbers. Not the whole network though, because some lines don't connect at all with other lines. I don't know if this is intended or if it comes from snapping issues. You might have to correct this manually.

Hope this will help you (and thanks for the beta testing ;) ).

**Comment by malleeblue** [comment]
Hi,

Thank you very much for your quick answer!! Wow!

I knew that there were topology issues with the layer. Addressing those is one of my tasks, so thank you for pointing out those specific issues.

And I need to thank you for the plug in. It will assist us enormously with analysis of flow. I often get asked if I am worried about using QGIS – free software – especially in terms of getting support. You are proof that open source software offers better support than proprietary software.

If you would like some assistance to document the plugin  (or your other Merge lines one) let me know. I can’t write code, but I can write sentences. If it helps other people to use your plugin, I’m happy to do it.

Johanna

**Comment by ArMoraer** [comment]
Thank you for your kind support! And don't hesitate to open a new 'issue' if you face a bug or need to add a specific feature (I am quite open to feature requests).
